server:
  port: 8087

spring:
  application:
    name: file-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file_service_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 569811
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: public

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

minio:
  # 使用 Docker Nginx 反向代理方案
  # Nginx 监听 80 端口，代理到 MinIO 容器
  # 明确指定端口 80，避免 SDK 尝试使用 HTTPS(443)
  endpoint: http://192.168.141.128:80
  access-key: minio
  secret-key: minio123456
  bucket-name: education-files

